### ISSUE TITLE
base64 module error

### ISSUE THREAD

**Issue by rainbat** [thody/github-issue-reports#5]
Hi there,
just tried your node.js github issue reports generator ...

I'm running into this error, any ide ?

Error: Cannot find module 'base64'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/github-issue-reports/src/report-generator.js:8:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/github-issue-reports/bin/github-issue-reports.js:24:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

Thanks in advance, Dom

**Comment by thody** [comment]
@rainbat just released a patch, you should be good to go with the latest version.
